export const LANGUAGE_ICONS = {
    'Assembly': '',
    'C#': 'devicon-csharp-line',
    'C': '',
    'C++': 'devicon-cplusplus-line',
    'CSS': 'devicon-css3-plain-wordmark',
    'CoffeeScript': 'devicon-coffeescript-original-wordmark',
    'Elm': '',
    'Go': 'devicon-go-line',
    'Groovy': '',
    'HTML': 'devicon-html5-plain-wordmark',
    'Haskell': '',
    'Java': 'devicon-java-plain-wordmark',
    'JavaScript': 'devicon-javascript-plain',
    'Kotlin': '',
    'Lua': 'prlang lua-icon',
    'Objective-C': '',
    'PHP': 'devicon-php-plain',
    'Pascal': '',
    'Perl': '',
    'Python': 'devicon-python-plain-wordmark',
    'R': '',
    'Ruby': 'devicon-ruby-plain-wordmark',
    'Rust': 'prlang rust-icon',
    'Scala': '',
    'Shell': 'prlang shell-icon',
    'Swift': '',
    'TeX': '',
    'TypeScript': 'devicon-typescript-plain',
    'Visual Basic': ''
}