export const LANGUAGE_ICONS = {
    'Assembly': 'prlang assembly-icon',
    'C#': 'devicon-csharp-line',
    'C++': 'devicon-cplusplus-line',
    'CSS': 'devicon-css3-plain-wordmark',
    'CoffeeScript': 'devicon-coffeescript-original-wordmark',
    'Elm': 'prlang elm-icon',
    'Go': 'devicon-go-line',
    'HTML': 'devicon-html5-plain-wordmark',
    'Haskell': 'prlang haskell-icon',
    'Java': 'devicon-java-plain-wordmark',
    'JavaScript': 'devicon-javascript-plain',
    'Kotlin': 'prlang kotlin-icon',
    'Lua': 'prlang lua-icon',
    'Objective-C': 'prlang objc-icon',
    'PHP': 'devicon-php-plain',
    'Perl': 'prlang perl-icon',
    'Python': 'devicon-python-plain-wordmark',
    'Ruby': 'devicon-ruby-plain-wordmark',
    'Rust': 'prlang rust-icon',
    'Scala': 'prlang scala-icon',
    'Shell': 'prlang shell-icon',
    'Swift': 'prlang swift-icon',
    'TeX': 'prlang tex-icon',
    'TypeScript': 'devicon-typescript-plain',
}